<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Epi.ContentCore\Epi.ContentCore.csproj" />
    <ProjectReference Include="..\Epi.Signature\Epi.Signature.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Epi.Iam</RootNamespace>
  </PropertyGroup>

</Project>
