<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Epi.ContentCore\Epi.ContentCore.csproj" />
    <ProjectReference Include="..\Epi.Contracts\Epi.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Epi.Governance</RootNamespace>
  </PropertyGroup>

</Project>
