<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Epi.ContentCore\Epi.ContentCore.csproj" />
    <ProjectReference Include="..\Epi.Contracts\Epi.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>Epi.Governance</RootNamespace>
  </PropertyGroup>

</Project>
