<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Epi.Validation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Firely.Fhir.Validation.R5" Version="3.3.1" />
    <PackageReference Include="Hl7.Fhir.Specification.Data.R5" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Epi.ContentCore\Epi.ContentCore.csproj" />
  </ItemGroup>

</Project>
